### Arrays & Data frames - NumPy tutorial

### Import NumPy

Once NumPy is installed, import it in your applications by adding the import keyword:

import numpy

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### NumPy as np
 

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Checking NumPy Version

The version string is stored under __version__ attribute.

In [3]:
import numpy as np

print(np.__version__)

1.26.4


### NumPy Creating Arrays


#### Create a NumPy ndarray Object
 

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method

In [4]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


### Dimensions in Arrays


0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [5]:
import numpy as np

arr = np.array(4)

print(arr)

4


1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [7]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions using 
  ndim

In [8]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays define the number of dimensions by using the ndmin

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### Array Indexing

Access Array Elements 

You can access an array element by referring to its index number.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

#Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])

1
2
7


#####  Access 2-D Arrays

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 2st row: ', arr[1, 1])

2nd element on 1st row:  2
2nd element on 2st row:  7


#####  Access 3-D Arrays

In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr )
print(arr[0, 1, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


#####  Negative Indexing 

In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('  element from 2nd dim: ', arr[1, -1])
print('  element from 1nd dim: ', arr[0, -2])

  element from 2nd dim:  10
  element from 1nd dim:  4


### NumPy Array Slicing

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[2:5])
print(arr[3:6])
print(arr[3:7])

[2 3 4 5]
[3 4 5]
[4 5 6]
[4 5 6 7]


In [20]:
#Slice elements from index 3 to the end of the array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[3:])

[4 5 6 7]


In [21]:
#Slice elements from the beginning to index 3 (not included):
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:3])

[1 2 3]


##### Negative Slicing

 

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-1])

[4 5 6]


##### STEP
 

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [10]:
#Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


#####  Slicing 2-D Arrays

In [27]:
#From the 1st element, slice elements from index 1 to index 5 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [24]:
#From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:5, 2])

[3 8]


In [26]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:3])

[[2 3]
 [7 8]]


### Data Types in Python


strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

### Data Types in NumPy

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

#### Checking the Data Type

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [36]:
#data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [37]:
#Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [38]:
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [39]:
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [40]:
#Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [41]:
#Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### Array Copy vs View

the copy is a new array, and the view is just a view of the original array.

The copy any changes made to the original array will not affect the copy.

The view  any changes made to the original array will affect the view.

In [44]:
#Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 33

print(arr)
print(x)

[33  2  3  4  5]
[1 2 3 4 5]


In [46]:
#Make a view, change the original array, and display both arrays:
#The view SHOULD be affected by the changes made to the original array.


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 30

print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4  5]


### NumPy Array Shape


The shape of an array is the number of elements in each dimension.



In [47]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [54]:
#Create an array with 4 dimensions using ndmin using a vector with values 1,2,3,4  
# and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4 ], ndmin=4)

print(arr)
print('shape of array :', arr.shape)

[[[[1 2 3 4]]]]
shape of array : (1, 1, 1, 4)


### Array Reshaping

Reshape From 1-D to 2-D

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
newarr1 = arr.reshape(3, 4)
newarr2 = arr.reshape(2, 6)

print(newarr)
print(newarr1)
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Reshape From 1-D to 3-D

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
newarr1 = arr.reshape(3, 2, 2)
newarr2 = arr.reshape(2, 2, 3)

print(newarr)
print("------")
print(newarr1)
print("------")
print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [62]:
#Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [27]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension 
# (will raise an error):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Python NumPy Array Creation - Empty, Zeroes and Ones

In [35]:
#Using numpy.empty Basic Example:
#create an empty array. Also, elements in an array will show random values because 
# they are not initialized:

import numpy as np 

# an array with 4 rows and 3 columns
x = np.empty([4,3], dtype = int) 
print (x)

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [6815836 6029424 7340097]
 [4456560 7602273      97]]


In [65]:
#Using numpy.zeroes Basic Example:
#The below code example will create an array of dimension 3x3 with all elements initialized as 0.
import numpy as np  

arr = np.zeros((3,3), dtype = int)  
print(arr)  

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [66]:
#Using numpy.ones Basic Example: 
import numpy as np  

arr = np.ones((3,3), dtype = int)  
print(arr)  

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Joining Array

In [67]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [86]:
#Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
arr1 = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("-------------------")
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------------
[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [84]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr = np.stack((arr1, arr2, arr3), axis=1)

print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis. It returns a NumPy array. to join 2 arrays, they must have the same shape and dimensions.

### Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [87]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [88]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Splitting Array

In [89]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [90]:
#Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Splitting 2-D Arrays

In [91]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [92]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


### Searching Arrays

In [93]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) # the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [94]:
#Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


### Sorting Arrays

In [95]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
#Note: This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [96]:
#Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [97]:
#Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [98]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays

In [100]:
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [101]:
#Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### NumPy ufuncs

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation

### What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [102]:
#With ufunc, we can use the add() function:

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


### Create Your Own ufunc


How To Create Your Own ufunc
 

The frompyfunc() method takes the following arguments:

function - the name of the function.

inputs - the number of input arguments (arrays).

outputs - the number of output arrays.

In [103]:
#Create your own ufunc for addition:

import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


Check if a Function is a ufunc


In [105]:
import numpy as np

print(type(np.add))

#Check the type of another function: concatenate():

print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [106]:
#Use an if statement to check if the function is a ufunc or not:

import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


### Simple Arithmetic


In [107]:
#Add the values in arr1 to the values in arr2:

import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [108]:
#Subtract the values in arr2 from the values in arr1:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


### Rounding Decimals


Truncation
Remove the decimals, and return the float number closest to zero.

In [109]:
#Truncate elements of following array:

import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [110]:
#Same example, using fix():

import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

In [2]:
import numpy as np

arr = np.around(3.1666, 3)

print(arr)

3.167


Log at Base 2

Use the log2() function to perform log at the base 2.

In [4]:
import numpy as np

arr = np.arange(1, 10)
print( arr )
print(np.log2(arr))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


Log at Base 10

Use the log10() function to perform log at the base 10.

In [113]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Natural Log, or Log at Base e

Use the log() function to perform log at the base e.

In [114]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### NumPy Summations


In [115]:
#Add the values in arr1 to the values in arr2:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [116]:
#Sum the values in arr1 and the values in arr2:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [120]:
#Perform summation in the following array over 1st axis:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)
#NumPy will sum the numbers in each array.
newarr2 = np.sum([arr1, arr2], axis=0)
print(newarr)
print(newarr2)

[6 6]
[2 4 6]


#### Cummulative Sum

Cummulative sum means partially adding the elements in array.

In [122]:
#Perform cummulative summation in the following array:

import numpy as np

arr = np.array([1, 2, 3,4,5])

newarr = np.cumsum(arr)

print(newarr)

[ 1  3  6 10 15]


### Products

Product in math is the result of two or more numbers when multiplied together.

In [123]:
#Find the product of the elements of this array:

import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [124]:
#Find the product of the elements of two arrays:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [125]:
#Perform summation in the following array over 1st axis:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [126]:
##cummulative product of all elements for following array:

import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


### Differences

A discrete difference means subtracting two successive elements.

In [127]:
#Compute discrete difference of the following array:

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [128]:
#Compute discrete difference of the following array twice:

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)
#15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30

[  5 -30]


### NumPy Boolean Indexing

Boolean indexing allows us to filter elements from an array based on a specific condition.

We use boolean masks to specify the condition.

 


1D Boolean Indexing in NumPy

In [129]:
#the boolean indexing to select only the odd numbers from an array.

import numpy as np

# create an array of numbers
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# create a boolean mask
boolean_mask = array1 % 2 != 0

# boolean indexing to filter the odd numbers
result = array1[boolean_mask]

print(result)

# Output: [ 1  3  5  7 9]

[1 3 5 7 9]


Example: 1D Boolean Indexing in NumPy

In [130]:
import numpy as np

# create an array of integers
array1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])

# create a boolean mask using combined logical operators
boolean_mask = (array1 < 10) | (array1 > 40)

# apply the boolean mask to the array 
result = array1[boolean_mask]

print(result)

# Output: [ 1  2  4  9 47 51 52]

[ 1  2  4  9 47 51 52]


Modify Elements Using Boolean Indexing

In [131]:
import numpy as np

# create an array of numbers
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# make a copy of the array
numbers_copy = numbers.copy()

# change all even numbers to 0 in the copy
numbers_copy[numbers % 2 == 0] = 0

# print the modified copy
print(numbers_copy)

# Output: [1 0 3 0 5 0 7 0 9 0]

[1 0 3 0 5 0 7 0 9 0]


2D Boolean Indexing in NumPy

Boolean indexing can also be applied to multi-dimensional arrays in NumPy.

In [132]:
import numpy as np

# create a 2D  array
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = array1 > 9

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)

[14 19 21 25 29 35]
